// src/lib/wpa/index.ts
//
// Next-side wiring for WPA: loads the versioned model config and the
// precomputed win-probability table (generated by scripts/generate-wpa-table.mjs
// — regenerate with `npm run gen:wpa` after any model change), and exposes a
// request-cached season computation. Only table lookups happen at request time;
// the convolution never runs here.
//
// The model is versioned (see wpa-model-2026.json). A future-season refit gets
// its own config + table files so 2026 figures remain reproducible.

import { cache } from 'react';
import { getAllData, extractUniqueMatches, toSlug } from '@/lib/data';
import { getTeamSlugByName } from '@/lib/teams';
import { computeSeasonComebacks, type SeasonComebacks } from './comebacks';
import {
  computeSeasonWpa,
  computeMatchWpa,
  wpLookup,
  liLookup,
  cnWpaFor,
  type WpTable,
  type LiTable,
  type WpaModelConfig,
  type SeasonWpa,
  type MatchWpa,
  type FighterWpa,
} from './core';
import tableJson from './wp-table-2026.json';
import liTableJson from './li-table-2026.json';
import modelJson from './wpa-model-2026.json';

export const WPA_TABLE = tableJson as WpTable;
export const LI_TABLE = liTableJson as LiTable;
export const WPA_MODEL = modelJson as unknown as WpaModelConfig & {
  gamma: number;
  marginDistribution: Record<string, number>;
  dqRuleReason: string;
  referenceTotals: { name: string; wpa: number }[];
  checksums: { d: number; r: number; wp: number }[];
  // Frozen 2026 Leverage / Clutch constants.
  liNormalizer: number;
  cnScale: number;
  liChecksums: { d: number; r: number; li: number }[];
  liReferenceTotals: {
    name: string;
    rounds: number;
    avgLi: number;
    wpa: number;
    cnWpa: number;
    clutch: number;
  }[];
};
export const WPA_MODEL_VERSION = WPA_TABLE.modelVersion;

export type { SeasonWpa, MatchWpa, FighterWpa };
export type { MatchComeback, TeamComebackTotals, SeasonComebacks, ComebackDriver } from './comebacks';
export { COMEBACK_THRESHOLD, computeMatchComeback, comebackDrivers } from './comebacks';
export { wpLookup, liLookup, cnWpaFor, computeMatchWpa };

// Season WPA for every fighter and match, derived from the same match data the
// rest of the site uses. React cache() dedupes within a request; the underlying
// CSVs are ISR-cached in getAllData.
export const getWpaData = cache(async (): Promise<SeasonWpa> => {
  const data = await getAllData();
  const matches = extractUniqueMatches(data.teamMatches);
  return computeSeasonWpa(matches, WPA_TABLE, WPA_MODEL, toSlug, LI_TABLE);
});

// Comebacks & blown leads for the season, derived from the same stored win
// probabilities. Request-cached like getWpaData.
export const getComebackData = cache(async (): Promise<SeasonComebacks> => {
  const season = await getWpaData();
  return computeSeasonComebacks(season, getTeamSlugByName);
});

// A fighter's WPA rank (1-based) over qualified fighters isn't needed; the
// leaderboard sorts live. This helper returns one fighter's season WPA record.
export async function getFighterWpa(slug: string): Promise<FighterWpa | null> {
  const season = await getWpaData();
  return season.byFighter.get(slug) ?? null;
}
